# Usage: uv run capx/envs/launch.py --config-path env_configs/real/real_qwen_exps.yaml

env:
  _target_: capx.envs.tasks.franka.franka_lift.FrankaLiftCodeEnv
  # _target_: capx.envs.tasks.franka.franka_pick_place.FrankaPickPlaceCodeEnv
  cfg:
    _target_: capx.envs.tasks.base.CodeExecEnvConfig
    low_level: franka_real_low_level
    privileged: false
    apis:
      - FrankaRealControlApi
    task_only_prompt: "pick up the red cube and lift it"
    prompt: |
      You are controlling a Franka Emika robot with API described below.
      Goal: pick up the red cube and lift it.
      You may write python code comments for reasoning but ONLY write the executable Python code and do not write it in code fences.
      The functions (APIs) below are already imported to the environment. If you want to use numpy, you need to import it explicitly.

api_servers:
  - _target_: capx.serving.launch_sam3_server.main
    device: cuda
    port: 8114
    host: 127.0.0.1
    
  - _target_: capx.serving.launch_contact_graspnet_server.main
    port: 8115
    host: 127.0.0.1

  - _target_: capx.serving.launch_pyroki_server.main
    port: 8116
    host: 127.0.0.1
    robot: panda_description
    target_link: panda_hand

record_video: true
# use_img_differencing: true
# output_dir: ./outputs/franka_cube_lift_oracle
# output_dir: ./outputs/franka_cube_stack_qwen_post_rl
output_dir: ./outputs/franka_cube_lift_oracle_25
use_oracle_code: true

trials: 1
num_workers: 1