# Usage: uv run capx/envs/launch.py --config-path env_configs/human_oracle_code/robosuite/franka_robosuite_cube_stack_privileged_oracle.yaml

env:
  _target_: capx.envs.tasks.franka.franka_pick_place.FrankaPickPlaceCodeEnv
  cfg:
    _target_: capx.envs.tasks.base.CodeExecEnvConfig
    low_level: franka_robosuite_cubes_low_level
    privileged: true
    apis:
      - FrankaControlPrivilegedApi
    # prompt is inherited from FrankaPickPlaceCodeEnv class default

api_servers:
  - _target_: capx.serving.launch_pyroki_server.main
    port: 8116
    host: 127.0.0.1
    robot: panda_description
    target_link: panda_hand
    
record_video: true
output_dir: ./outputs/franka_robosuite_cube_stack_privileged_oracle

trials: 100
num_workers: 10
use_oracle_code: true
